In [2]:
import pandas as pd
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]], columns=["A","B","C"],index=["x","y","z"])

In [3]:
df.index.tolist()

['x', 'y', 'z']

In [4]:
df.info()
df.nunique()
df['A'].unique()
df.shape

<class 'pandas.DataFrame'>
Index: 3 entries, x to z
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 99.0 bytes

(3, 3)

In [5]:
df.describe()

         A    B    C
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0

In [6]:
coffee = pd.read_csv('./coffee.csv')

# Loading in Dataframes from files

In [7]:
coffee.head(5)

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [8]:
results = pd.read_csv("https://raw.githubusercontent.com/KeithGalli/complete-pandas-tutorial/refs/heads/master/data/results.csv")

In [9]:
results.head(5)

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN

## pd.read_csv(): 
- Best for simple, human-readable, and lightweight data. Slower parsing, larger file sizes, and prone to losing data types (e.g., stripping leading zeros)

## pd.read_excel():
- Designed for working directly with Excel spreadsheets. It is the slowest of the three and may choke on files exceeding 100,000 rows.

## pd.read_parquet():
- The gold standard for data science and large datasets. It uses a binary columnar format, offering lightning-fast read speeds, up to 75% smaller file sizes, and strict data-type preservation

In [10]:
coffee=pd.read_csv('./coffee.csv')

In [11]:
results=pd.read_parquet('~/Downloads/results.parquet')

In [12]:
bios=pd.read_csv('https://raw.githubusercontent.com/KeithGalli/complete-pandas-tutorial/refs/heads/master/data/bios.csv')

# Accessing datas with pandas

In [14]:
coffee.sample(10,random_state=1)

          Day Coffee Type  Units Sold
3     Tuesday       Latte          20
7    Thursday       Latte          30
6    Thursday    Espresso          40
2     Tuesday    Espresso          30
10   Saturday    Espresso          45
4   Wednesday    Espresso          35
1      Monday       Latte          15
12     Sunday    Espresso          45
0      Monday    Espresso          25
13     Sunday       Latte          35

In [24]:
coffee.loc[5:12,["Day","Units Sold"]]

          Day  Units Sold
5   Wednesday          25
6    Thursday          40
7    Thursday          30
8      Friday          45
9      Friday          35
10   Saturday          45
11   Saturday          35
12     Sunday          45

In [22]:
coffee.iloc[5:12,[0,1]]

          Day Coffee Type
5   Wednesday       Latte
6    Thursday    Espresso
7    Thursday       Latte
8      Friday    Espresso
9      Friday       Latte
10   Saturday    Espresso
11   Saturday       Latte

In [ ]:
coffee.index